### PR TITLE
Various fixes

### LINKED ISSUE #86: Cannot read property 'closeTimeout' of null
When I visit http://localhost:8080/UniformDocs/FileUpload in Chrome with Starcounter DevTools 3.3.1 installed, I get the following error in console:

```
Uncaught TypeError: Cannot read property 'closeTimeout' of null
    at e (injected_script.js:1)
    at window.addEventListener (injected_script.js:4)
```

screen shot 2018-06-19 at 11 56 16

### PR DESCRIPTION
**Pull request by alshakero**
Fixes #86, #92, #95 and #46.

### CODE REVIEW

**Comment by alshakero** [comment]
Ping @warpech

File: src/palindrom-js-listener.js [hunk 1]
```diff
@@ -187,6 +192,7 @@
 
         client.addEventListener('patchreceived', this.onPatchReceived);
         client.addEventListener('patchsent', this.onPatchSent);
+        client.addEventListener('patch-applied', this.onPatchApplied);
```
Comment (tomalec) [inline src/palindrom-js-listener.js]: You need to remove this listener later, don't you?

Comment (alshakero) [reply src/palindrom-js-listener.js]: Right!
